version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://admin:HereiterNu%410@symfony.cnauwe826vmx.eu-north-1.rds.amazonaws.com:3306/symfony
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: HereiterNu%410
      MYSQL_DATABASE: symfony
      MYSQL_USER: admin
      MYSQL_PASSWORD: HereiterNu%410
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
